stages:
  - name: Build & Publish
    when:
      branch: not-this-branch
      event: [push, pull request]
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: cloud-bot:${CICD_EXECUTION_SEQUENCE}
        env:
          ### IMPORTANT ###
          # This is a workaround
          # Needed to be your MTU - 50
          # My MTU is 1500 so env set to 1450
          PLUGIN_MTU: 1450
  - name: Deploy
    when:
      branch: not-this-branch
      event: [push, pull request]
    steps:
      - applyYamlConfig:
          path: ./cloud_bot/bot-dc.yaml

branch:
  include:
    - not-this-branch
