stages:
  - name: Build & Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: twitter-bot:v1.0
        env:
          PLUGIN_MTU: "1230"
    when:
      branch: {}
      event:
        include:
          - push
          - pull request
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./bot-dc.yaml
    when:
      branch: {}
      event:
        include:
          - push
          - pull request
branch:
  include:
    - coding-specific
notification: {}
