apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-bot
  namespace: bots
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twitter-bot
  template:
    metadata:
      labels:
        app: twitter-bot
    spec:
      imagePullSecrets:
        - name: guldentech-harbor-registry
      containers:
        - name: twitter-bot
          image: harbor.guldentech.com/austin-spencer/twitter-bot:TAG
          imagePullPolicy: Always
          env:
            - name: CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: CONSUMER_KEY
                  name: tendie-twitter-bot
            - name: CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: CONSUMER_SECRET
                  name: tendie-twitter-bot
            - name: KEY
              valueFrom:
                secretKeyRef:
                  key: KEY
                  name: tendie-twitter-bot
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  key: SECRET
                  name: tendie-twitter-bot
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: redis
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASS
                  name: redis
